window.NEWS_ENTRIES = [
  {
    date: "2026-03-06",
    title: "Antwortschreiben des Staatsministeriums zur Petition WI.0084.19",
    text: "Das StMWi teilt mit, dass laut vorliegenden Fachgutachten keine erhebliche Umfassungswirkung mit unzumutbarer Beeinträchtigung zu erwarten sei. Gleichzeitig sei das Verfahren im RPV Donau-Wald noch nicht abgeschlossen.",
    url: "sources/2026-03-06_antwortschreiben-ministerium-petition-wi-0084-19.pdf",
  },
  {
    date: "2026-02-10",
    title: "Windpark 3 (Hayforst): UVP ist durchzuführen",
    text: "Die allgemeine Vorprüfung ergab, dass erhebliche nachteilige Umweltauswirkungen möglich sind; ausschlaggebend sind unter anderem die Rodungen, Habitatverluste und Unsicherheiten bei Kompensationsmaßnahmen.",
    url: "http://www.uvp-verbund.de/trefferanzeige?docuuid=1697277f-1ff2-4c6b-817b-d895ab5a6db7&q=&ct=true&rstart=0&currentSelectorPage=1&f=type%3Aflurbereinigung%3Bprocedure%3Aprocedure_10_time%3Bprocedure%3Aprocedure_12_time%3Bprocedure%3Aprocedure_13_time%3Bprocedure%3Aprocedure_14_time%3Bprocedure%3Aprocedure_11_time%3B&category=chemie%3Bholzzellstoff%3Bkernenergie%3Bbaustoffe%3Benergie%3Bbauvorhaben%3Bflurbereinigung&modtime=last_month%3Blast_year&procedure=obj_class_zv&provider=ni%3Bby",
  },
  {
    date: "2026-02-01",
    title: "Unterlagen und Neuigkeiten veröffentlicht",
    text: "EjUn bündelt Petition, BR24-Beitrag, Stellungnahmen und weitere Hintergrunddokumente in einem Sammelbeitrag im Bereich Dokumente/News.",
    url: "sources/ejun/2026-02-01_unterlagen-neuigkeiten.html",
    sourceUrl: "https://www.buergerinitiative-ejun.de/docs/post/unterlagen-neuigkeiten-vom-01.02.2026",
  },
  {
    date: "2025-12-11",
    title: "Petition: Antwort der Regierung",
    text: "Die Bürgerinitiative verlinkt das Dokument zum Ergebnis der Petition als eigenes PDF.",
    url: "sources/ejun/2025-12-11_petition-antwort-ergebnis-der-regierung.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/2025_12_11%20Petition-%20Antwort%20Ergebnis%20der%20Regierung.pdf",
  },
  {
    date: "2025-11-29",
    title: "BR24-Beitrag zur Umzingelung",
    text: "Im Sammelbeitrag wird ein BR24-Video zur Situation in Franken-Neuhofen verlinkt.",
    url: "https://www.youtube.com/watch?v=r464eFlL1xM",
    sourceUrl: "https://www.buergerinitiative-ejun.de/docs/post/unterlagen-neuigkeiten-vom-01.02.2026",
  },
  {
    date: "2025-10-06",
    title: "Stellungnahme an den Planungsverband",
    text: "EjUn stellt eine eigene Stellungnahme gegen den Planungsverband Donau-Wald als PDF bereit.",
    url: "sources/ejun/2025-10-06_stellungnahme-ejun-gegen-planungsverband-donau-wald.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/2025_10_06%20Stellungnahme%20EjUn%20gegen%20Planungsverband%20Donau-Wald.pdf",
  },
  {
    date: "2025-06-06",
    title: "Öffentliche Petition veröffentlicht",
    text: "Die öffentliche Petition zur Windkraft-Umzingelung von Franken-Neuhofen wird als vollständiges PDF bereitgestellt.",
    url: "sources/ejun/2025-06-06_public-petition-windkraft-umzingelung-franken-neuhofen.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/Dokumente/2025_06_06%20Public%20Petition%20Windkraft%20Umzingelung%20Franken-Neuhofen.pdf",
  },
  {
    date: "2025-05-26",
    title: "Stellungnahme von Planungsverband und Landrat",
    text: "Als eingegangene Antwort auf das Mai-Schreiben wird eine gemeinsame Stellungnahme von Planungsverband Donau-Wald und Landrat Laumer abgelegt.",
    url: "sources/ejun/2025-05-26_stellungnahme-planungsverband-donau-wald-und-landrat-laumer.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/Dokumente/2025_05_26%20Stellungnahme%20Planungsverband%20Donau-Wald%20und%20Landrat%20Laumer.pdf",
  },
  {
    date: "2025-05-11",
    title: "Schreiben an Landrat Laumer nach rundem Tisch",
    text: "EjUn legt ein Schreiben zur Entlastung von Franken-Neuhofen durch optimierte Planung vor und verweist darin auf mehrere Anhänge als Argumentationsgrundlage.",
    url: "sources/ejun/2025-05-11_entlastung-franken-neuhofen-durch-optimierte-planung-windvorrangflaechen.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/Dokumente/2025_05%20Entlastung%20Franken-Neuhofen%20durch%20optimierte%20Planung%20Windvorrangfl%C3%A4chen.pdf",
  },
  {
    date: "2025-03-12",
    title: "Gutachten zu Umfassung und Umzingelung verlinkt",
    text: "Als Anhang zum Schreiben an den Landrat wird ein Gutachten von Martin Stümpfig zur Umfassung und Umzingelung referenziert.",
    url: "sources/ejun/2025-03-12_stuempfig-gutachten-umfassung-2021.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/Dokumente/2025_03_12%20St%C3%BCmpfig-%20Gutachten%20Umfassung%202021.pdf",
  },
  {
    date: "2025-03-07",
    title: "Zeitungsbericht zu Windkraft Eldorado wider Willen",
    text: "Ein Bericht der Allgemeinen Laber Zeitung zur regionalen Debatte wird als PDF archiviert.",
    url: "sources/ejun/2025-03-07_allgemeine-laber-zeitung-windkraft-eldorado-wider-willen.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/Dokumente/2025_03_07%20Allgemeine%20Laber%20Zeitung-%20Windkraft%20Eldorado%20wider%20Willen.pdf",
  },
  {
    date: "2025-03-01",
    title: "Hintergrundpapier zu Wirtschaftlichkeit und Umzingelung",
    text: "Ein im Dateinamen nur auf März 2025 datiertes Hintergrundpapier zur Unwirtschaftlichkeit und umzingelnden Wirkung von Windkraftanlagen wird als Anhang geführt.",
    url: "sources/ejun/2025-03_unwirtschaftlichkeit-und-umzingelnde-wirkung-von-wka-aus-2013.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/Dokumente/2025_03%20Unwirtschaftlichkeit%20und%20umzingelnde%20Wirkung%20von%20WKA%20aus%202013.pdf.pdf",
  },
  {
    date: "2024-12-16",
    title: "Rückmeldung des Planungsverbands Donau-Wald",
    text: "Die Rückmeldung des Planungsverbands zur Thematik Umzingelung ist als PDF hinterlegt.",
    url: "sources/ejun/2024-12-16_antwort-laumer-regionaler-planungsverband.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/Dokumente/2024_12%20Antwort%20Laumer-%20Regionaler%20Planungsverband.pdf",
  },
  {
    date: "2024-07-09",
    title: "Bürgermeisterschreiben zu Windvorranggebieten",
    text: "Ein Bürgermeisterschreiben zu Windvorranggebieten wird als ergänzender Anhang verlinkt.",
    url: "sources/ejun/2024-07-09_windvorranggebiete-buergermeisterschreiben.pdf",
    sourceUrl: "https://www.buergerinitiative-ejun.de/Dokumente/2024_07_09%20Windvorranggebiete%20B%C3%BCrgermeisterschreiben.pdf",
  },
  {
    date: "2024-06-23",
    title: "Treffen vom 23.06.2024",
    text: "Im frühen Treffen dokumentiert die Initiative politische Gespräche, geplante Flyer und Plakate sowie den Ausbau der Informationsarbeit in den betroffenen Gemeinden.",
    url: "treffen-23-06-2024.html",
    sourceUrl: "https://www.buergerinitiative-ejun.de/docs/post/treffen-vom-23.06.2024",
  },
];
